# Task 5: K-means clustering

### Importing required modules

In [18]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

### Reading data from file

In [19]:
data = pd.read_csv("kmeans.csv", delimiter=',', index_col='Object')
data.head()

X   Y  Cluster
Object                 
1        3  18        0
2       15  18        1
3       15   5        2
4       11   8        1
5        5  12        2

### Removing information about clusters

In [20]:
coords = data.drop('Cluster', axis=1)
coords.head()

X   Y
Object        
1        3  18
2       15  18
3       15   5
4       11   8
5        5  12

### Model initialization

In [21]:
# Centroid initial coordinates
centroid = np.array([[8.67, 12.67], [15.5, 9.75], [13.4, 12.6]])

# Generating k-means object
kmeans = KMeans(n_clusters=3, init=centroid, max_iter=100, n_init=1)

### Model training

In [22]:
model = kmeans.fit(coords)

### Assigning clusters

In [23]:
clusters_list = model.labels_.tolist()
print(clusters_list)

[0, 2, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1, 1]


### Distances calculation

In [24]:
alldistances = kmeans.fit_transform(coords)
print(alldistances)

[[ 7.26722093 17.12129928  9.20869155]
 [10.90011468 11.36392929  2.82842712]
 [10.90011468  1.86338998 13.68941197]
 [ 5.90021186  5.01386965 10.46900186]
 [ 1.3462912  12.07499712  9.63327566]
 [ 4.82830198  7.84042232 12.14907404]
 [10.26218788 13.87343585  1.61245155]
 [17.30065028  7.03364928 19.0682983 ]
 [ 3.71651719  7.22072634  9.92975327]
 [ 7.7014609  14.61068863  4.24264069]
 [ 8.11249037  2.85287379 11.4280357 ]
 [ 6.54312616 10.51057668  2.68328157]
 [11.52443057 12.36145443  2.86356421]
 [14.4676363   4.17997873 13.81303732]
 [ 9.76281209  5.33593686  7.44311763]]


### Calculation of average distance between centroid 0 and points 0

In [25]:
sum = 0
counter = 0
for i in range(len(clusters_list)):
    if clusters_list[i] == 0:
        counter+=1
        sum += alldistances[i, 0]
average_distance = sum / counter
print('Average distance for cluster 0:', average_distance)

Average distance for cluster 0: 4.28958282361114
